[package]
name = "data_feed"
version = "0.1.0"
edition = "2021"

[dependencies]
decimal = {path = "../decimal"}

serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
reqwest = { version = "0.12.2", features = ["json", "blocking"] }
log = "0.4.22"